### ISSUE TITLE
Mod Crashes Game on Load when New Version of Runes (0.9.13) in Use

### ISSUE THREAD

**Issue by DumbXBoxAcct** [cleannrooster/druids#1]
It looks like rolling Runes back to 0.9.12, though, is a workaround and there are no issues when you do.

Just a "heads up!"

**Comment by DumbXBoxAcct** [comment]
Also, I'm using MC 1.20.1 with Fabric Loader 0.15.11.

**Comment by cleannrooster** [comment]
Should be fixed with recent update
