### ISSUE TITLE
[Fabric 1.20.1] crash on launch

### ISSUE THREAD

**Issue by memphismc** [cleannrooster/druids#3]
[crash-2024-06-30_12.50.57-client.txt](https://github.com/user-attachments/files/16043890/crash-2024-06-30_12.50.57-client.txt)

**Comment by Paxx3** [comment]
+1

**Comment by cleannrooster** [comment]
Hi, you're not on the newest version of Druids.

**Comment by memphismc** [comment]
> Hi, you're not on the newest version of Druids.

i realised this 20 minutes after submitting the issue as i thought i had the latest version which i got from modrinth then found out that the actual latest version is on curseforge

please keep the modrinth page for the mod updated, not just the curseforge one, a lot more people are using modrinth + mod menu notifies users about an update when you make updates

**Comment by cleannrooster** [comment]
I keep forgetting to keep modrinth updated, sorry about that.
